### ISSUE TITLE
Could not parse JavaScript from '(input)'. Unexpected token (4:0)

### ISSUE THREAD

**Issue by H1D** [videojs/videojs-4to5#3]
got this error:

``` bash
/usr/local/lib/node_modules/videojs-4to5/node_modules/grasp/lib/index.js:211
        throw new Error("Error: Could not parse JavaScript from '" + name + "'. " + e.message);
        ^

Error: Error: Could not parse JavaScript from '(input)'. Unexpected token (4:0)
    at search (/usr/local/lib/node_modules/videojs-4to5/node_modules/grasp/lib/index.js:211:15)
    at run (/usr/local/lib/node_modules/videojs-4to5/node_modules/grasp/lib/index.js:395:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/videojs-4to5/node_modules/grasp/lib/index.js:435:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/videojs-4to5/node_modules/grasp/lib/index.js:452:44)
    at Object.replacer (/usr/local/lib/node_modules/videojs-4to5/node_modules/lodash/index.js:3324:46)
    at Object.<anonymous> (/usr/local/lib/node_modules/videojs-4to5/src/main.js:41:35)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

To reproduce:

``` bash
cd /tmp
git clone https://github.com/walsh9/videojs-transcript.git
cd videojs-transcript
videojs-4to5 src
```

**Comment by misteroneill** [comment]
This is because the `videojs-transcript` project has multiple invalid/unparseable `.js` files (`intro.js`, `outro.js`, and `events.js`). The library behind the scenes, Grasp, needs to be able to parse input into a JavaScript AST to work.

These failures are expected.

In these cases, I'd recommend calling `videojs-4to5` only on those `.js` files that are parse-able.
